#Build stage
FROM golang:alpine as builder
RUN mkdir /builder
ADD . /build/
WORKDIR /build
RUN go build -o main .

#Final image
FROM alpine
RUN adduser -S -D -H -h /app appuser
USER appuser
COPY --from=builder /build/main /app/
WORKDIR /app
CMD ["./main"]
